// This file is auto-generated by scripts/generate-projects.mjs
// Do not edit by hand — edit content/projects/*.md and re-run generate.
import type { Project } from "./project-types";

export const projects: Project[] = [
  {
    "slug": "liftw",
    "title": "Liftw",
    "date": "2026-07-28",
    "category": "Fullstack",
    "status": "Live",
    "featured": true,
    "link": "https://liftw.xyz",
    "stack": [
      "Next.js",
      "Postgres",
      "Prisma",
      "MCP"
    ],
    "preview": "Liftw is a private gym tracker: log workouts, track volume and PRs, and optionally connect AI coaches through MCP — with…",
    "content": "**Liftw** is a private gym tracker: log workouts, track volume and PRs, and optionally connect AI coaches through MCP — without a social feed or locked-in chatbot.\n\nSite: [liftw.xyz](https://liftw.xyz)\n\n## Why it exists\n\nMost gym apps push social noise or hide your data behind a closed AI. Liftw is private-by-default: you own the log, and you choose when an agent gets a revocable API key.\n\n## What it does\n\n- Log sessions — exercises, sets, weight, reps, RPE, warmups\n- Session + rest timers; optional calorie estimates\n- Progress charts: volume, muscle balance, estimated 1RM, PRs\n- MCP-ready APIs so tools like Claude/Cursor can coach from your real history\n- Auth, onboarding, profile, and account controls\n\n## Stack notes\n\nNext.js + TypeScript on the web, Postgres/Prisma for the log, and an MCP surface for optional AI coaching. Built for people who actually train and want numbers they can trust."
  },
  {
    "slug": "lfm",
    "title": "lfm",
    "date": "2026-07-26",
    "category": "Misc",
    "status": "Live",
    "featured": true,
    "link": "https://lfm.aniketdhakane.xyz/",
    "stack": [
      "Go",
      "macOS",
      "Last.fm",
      "Discord"
    ],
    "preview": "lfm (linkFM) is a tiny local macOS daemon that watches what you’re playing in Apple Music, scrobbles it correctly to Las…",
    "content": "**lfm** (linkFM) is a tiny local macOS daemon that watches what you’re playing in Apple Music, scrobbles it correctly to Last.fm, and optionally mirrors it on Discord Rich Presence.\n\nSite: [lfm.aniketdhakane.xyz](https://lfm.aniketdhakane.xyz/) · Source: [github.com/watashiwaaniket/lfm](https://github.com/watashiwaaniket/lfm)\n\n## Why it exists\n\nI wanted scrobbling that respects Last.fm’s rules — no audio sniffing, no double-counts when you pause — and a single static binary I can install once and forget.\n\n## What it does\n\n- **Apple Music → Last.fm** via AppleScript + the official Last.fm API\n- **True scrobble rules**: track longer than 30s, then 50% played or 4 minutes\n- **Pause-aware timing**: wall-clock only while Music is actually playing\n- **Discord Rich Presence** (optional): track, artist, album art while you listen\n- **LaunchAgent**: `lfm install` starts at login; logs under `~/Library/Logs/lfm`\n\n## Architecture\n\n```\nlfm/\n├── apps/cli   # Go daemon (scrobbler + Discord RPC + launchd)\n└── apps/web   # Product landing → Cloudflare Workers\n```\n\nOne process handles both scrobbling and Discord presence. Prefer either LaunchAgent **or** `lfm run`, not both.\n\n## Install (short version)\n\n```bash\ngit clone https://github.com/watashiwaaniket/lfm.git\ncd lfm/apps/cli\ngo build -o lfm .\nlfm auth       # browser auth → session key\nlfm run        # foreground\n# or\nlfm install    # LaunchAgent background\n```\n\n## Takeaway\n\nA small systems-ish product: correct APIs, a boring reliable daemon, and a clean marketing surface for people who actually listen."
  },
  {
    "slug": "wiredraw",
    "title": "wiredraw",
    "date": "2025-06-01",
    "category": "Frontend",
    "status": "WIP",
    "featured": false,
    "link": "https://wiredraw.vercel.app/",
    "stack": [
      "Canvas",
      "TypeScript",
      "React"
    ],
    "preview": "wiredraw is a WIP Excalidrawstyle canvas for quick diagrams and whiteboarding on the web. Goals Fast freehand + shape sk…",
    "content": "**wiredraw** is a WIP Excalidraw-style canvas for quick diagrams and whiteboarding on the web.\n\n## Goals\n\n- Fast freehand + shape sketching\n- Keyboard-friendly editing where it matters\n- A calm default UI that stays out of the way\n\n## Status\n\nActively iterating. Expect rough edges — that’s part of the fun of building drawing tools in the browser."
  },
  {
    "slug": "personai",
    "title": "PersonAi",
    "date": "2025-04-12",
    "category": "Fullstack",
    "status": "Live",
    "featured": false,
    "link": "https://personai-rho.vercel.app/",
    "stack": [
      "Next.js",
      "AI",
      "TypeScript"
    ],
    "preview": "Ditch the dull notes. PersonAi is a smart, free second brain that remembers, summarizes, and thinks with you. What it do…",
    "content": "Ditch the dull notes. **PersonAi** is a smart, free second brain that remembers, summarizes, and thinks with you.\n\n## What it does\n\n- Capture thoughts, links, and notes without ceremony\n- Summarize long context into something you can act on\n- Act as a personal knowledge companion, not just a dump of text\n\n## Why I built it\n\nI wanted a second brain that felt light enough to use every day — something between a notebook and a chat interface, without the ceremony of a full wiki.\n\n## Stack notes\n\nBuilt as a fullstack web app with a focus on snappy UX and a calm reading surface. The goal was clarity over chrome: open it, write, get value back.\n\n> Live demo is linked from the project toolbar."
  },
  {
    "slug": "osap",
    "title": "osap",
    "date": "2025-02-18",
    "category": "Fullstack",
    "status": "Live",
    "featured": false,
    "link": "https://osaplfm.vercel.app/",
    "stack": [
      "Next.js",
      "Open Source"
    ],
    "preview": "osap is a platform for open source contributors to find the next interesting project to tinker with. Problem Finding goo…",
    "content": "**osap** is a platform for open source contributors to find the next interesting project to tinker with.\n\n## Problem\n\nFinding good open source work is noisy. READMEs vary wildly, “good first issue” labels go stale, and it’s hard to tell which repos are actually welcoming.\n\n## Approach\n\nSurface projects in a way that prioritizes **signal** — what the project is about, whether it’s active, and why it might be a good place to contribute.\n\n## Outcome\n\nA focused discovery surface for contributors who want something to ship against, not just star and forget."
  },
  {
    "slug": "codeseek",
    "title": "CodeSeek-r1",
    "date": "2025-01-08",
    "category": "Misc",
    "status": "Experiment",
    "featured": false,
    "link": null,
    "stack": [
      "AI",
      "Search"
    ],
    "preview": "CodeSeekr1 is an experimental take on codeaware search and retrieval — a misc project for exploring how far lightweight …",
    "content": "**CodeSeek-r1** is an experimental take on code-aware search and retrieval — a misc project for exploring how far lightweight AI workflows can go without a heavy product shell.\n\n## Intent\n\nPrototype first. Validate whether retrieval quality and UX feel good enough to grow into something larger.\n\n## What “done” means here\n\nNot a polished launch — a playground note with enough structure that future me (or a collaborator) can pick up the thread."
  },
  {
    "slug": "aura-protech",
    "title": "Aura ProTech Consulting",
    "date": "2024-11-05",
    "category": "Fullstack",
    "status": "Client",
    "featured": false,
    "link": "https://auraprotech.vercel.app/",
    "stack": [
      "Next.js",
      "CMS"
    ],
    "preview": "Client website for Aura ProTech Consulting — two landing pages plus a CMS for content updates. Scope Marketing landings …",
    "content": "Client website for **Aura ProTech Consulting** — two landing pages plus a CMS for content updates.\n\n## Scope\n\n- Marketing landings tuned for clarity and conversion\n- CMS-backed content so the team can update without deploys\n- Clean visual system that still feels professional\n\n## Notes\n\nClient work is about constraints: brand, timeline, and maintainability. This project was built to be easy for non-engineers to own after handoff."
  },
  {
    "slug": "alphatech",
    "title": "Alphatech Solutions",
    "date": "2024-09-20",
    "category": "Fullstack",
    "status": "Client",
    "featured": false,
    "link": "https://preview-alphatechsolutions.vercel.app/",
    "stack": [
      "Next.js",
      "Dashboard"
    ],
    "preview": "Landing page with a realtime dashboard for a training institute. Highlights Publicfacing marketing site Operational dash…",
    "content": "Landing page with a **realtime dashboard** for a training institute.\n\n## Highlights\n\n- Public-facing marketing site\n- Operational dashboard surface for live-ish training metrics\n- Structured so marketing and ops don’t fight over the same UI\n\n## Takeaway\n\nMixing marketing polish with dashboard density is hard — the trick is clear hierarchy and not letting either surface dilute the other."
  }
];
